# Generated by Django 6.0.3 on 2026-03-11 09:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('is_married', models.BooleanField()),
                ('has_children', models.BooleanField()),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('declared_address', models.CharField(max_length=255)),
                ('bank_history_months', models.IntegerField()),
                ('credit_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddressProof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.CharField(max_length=500)),
                ('extracted_name', models.CharField(max_length=255)),
                ('extracted_address', models.CharField(max_length=255)),
                ('extracted_date', models.DateField()),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_proof', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approved', models.BooleanField()),
                ('reason', models.CharField(max_length=255)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='RuleLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=255)),
                ('passed', models.BooleanField()),
                ('message', models.TextField()),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_logs', to='applications.decision')),
            ],
        ),
    ]
